# Generated by Django 5.2 on 2025-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='patient_images/'),
        ),
    ]
